"use client";
import type {CardInsight} from "@/lib/card-insights";
import {useState} from "react";
import Image from "next/image";
import {SalesActivityChart} from "./sales-activity-chart";
import type {ReviewCard} from "@/lib/review-data";
import {cardGuidance} from "@/lib/card-guidance";
import {estimate,type Settings} from "@/lib/selling-economics";
import {summarizePriceTrend,timingReadout} from "@/lib/price-trends";

type Plan="undecided"|"buylist"|"self"|"event"|"hold";
const choices:{id:Plan;label:string;icon:string}[]=[{id:"buylist",label:"Buylist",icon:"↗"},{id:"self",label:"Sell myself",icon:"◇"},{id:"event",label:"MagicCon",icon:"✦"},{id:"hold",label:"Hold",icon:"◷"}];
const cash=(n:number|null)=>n===null?"—":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(n/100);
const day=(s:string|null)=>s?new Date(s).toLocaleDateString("en-US",{month:"short",day:"numeric",timeZone:"UTC"}):"—";
const captureDay=(s:string|null)=>s?new Date(s).toLocaleDateString("en-US",{month:"short",day:"numeric",timeZone:"America/Los_Angeles"}):"—";
const channelLabel=(s:string)=>({ck_buylist:'Card Kingdom buylist',patient_self_sale:'Patient self-sale',advance_quote:'Advance cash quote',magiccon_quote:'MagicCon advance quote',alternative_buylist:'Compare other buylists',batch_bundle:'Bundle with a cash quote',verify:'Verify evidence',hold:'Hold / watch',compare:'Compare cash offers'}[s]??s.replaceAll('_',' '));
type Point={date:string;cents:number};

function History({card,asOf}:{card:ReviewCard;asOf:string}){
 const [days,setDays]=useState(90),[enabled,setEnabled]=useState<Record<string,boolean>>({ck:true,tcg:true,sales:true,ckRetail:false,manaPoolRetail:true,ckQuote:true,scgQuote:true}),[hover,setHover]=useState<Point&{label:string;capture:boolean}|null>(null);
 const end=Date.parse(asOf),start=end-days*86400000;
 const history=card.marketHistory as ReviewCard["marketHistory"]&{ckRetail?:Point[];manaPoolRetail?:Point[]};
 const quote=(cents:number|null,date:string|null):Point[]=>cents!==null&&date?[{cents,date}]:[];
 const allSeries=[
 {id:"ck",label:"CK buylist history",color:"#24765b",points:history.ck,kind:"line"},
 {id:"tcg",label:`TCG market reference · ${card.finish==="normal"?"nonfoil":card.finish}`,color:"#7c62bb",points:history.tcg,kind:"dash"},
 {id:"sales",label:"Mana Pool sales",color:"#d18c2f",points:card.recentSales,kind:"dots"},
 {id:"ckRetail",label:"CK retail reference",color:"#4f97a1",points:history.ckRetail??[],kind:"dash"},
 {id:"manaPoolRetail",label:"Mana Pool retail reference",color:"#ab7752",points:history.manaPoolRetail??[],kind:"dash"},
 {id:"ckQuote",label:`CK quote · ${card.ckSource==="direct_public"?"direct check":"TCGSentry"}`,color:"#164f3d",points:quote(card.ckCents,card.ckSourceDate),kind:"quote"},
 {id:"scgQuote",label:"SCG quote · TCGSentry",color:"#b15b71",points:quote(card.scgCents,card.scgSourceDate),kind:"quote"}];
 const series=allSeries.map(s=>({...s,points:summarizePriceTrend(s.points.filter(p=>Date.parse(p.date)>=start&&Date.parse(p.date)<=end)).points}));
 const shown=series.filter(s=>enabled[s.id]),points=shown.flatMap(s=>s.points),timing=timingReadout(card,asOf,days);
 const minPrice=Math.min(...points.map(p=>p.cents)),maxPrice=Math.max(...points.map(p=>p.cents));
 const padding=Math.max((maxPrice-minPrice)*.12,maxPrice*.02,1);
 const lo=Math.max(0,Math.floor(minPrice-padding)),hi=Math.ceil(maxPrice+padding);
 const x=(p:Point)=>48+((Date.parse(p.date)-start)/(end-start))*570,y=(n:number)=>174-(n-lo)/(hi-lo)*148;
 const amount=(n:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(n/100);
 const trend=summarizePriceTrend(history.tcg.filter(p=>Date.parse(p.date)>=start&&Date.parse(p.date)<=end));
 const delta=trend.changePercent;
 return <section className="decision-history"><div className="decision-section-head"><div><h3>Price history</h3><span>{delta!==null?`${delta>=0?"+":""}${delta}% TCG ${card.finish==="normal"?"nonfoil":card.finish} reference · ${days} days`:"Exact printing · prices per copy"}</span></div><div className="segmented" aria-label="History window">{[30,90].map(n=><button key={n} aria-pressed={days===n} onClick={()=>{setDays(n);setHover(null);}}>{n===30?"1M":"3M"}</button>)}</div></div>
 {points.length?<><svg className="price-chart" viewBox="0 0 650 205" role="img" aria-label={`Price history for ${card.name}, ${days} days, USD`}>
 {[0,.25,.5,.75,1].map(t=>{const value=lo+(hi-lo)*t;return <g key={t}><line x1="48" x2="618" y1={y(value)} y2={y(value)} stroke="#e7ebe7" strokeDasharray="3 4"/><text x="39" y={y(value)+4} textAnchor="end">{amount(value)}</text></g>;})}
 <text x="48" y="199">{day(new Date(start).toISOString())}</text><text x="618" y="199" textAnchor="end">{captureDay(asOf)}</text>
 {shown.map(s=><g key={s.id}>{(s.kind==="line"||s.kind==="dash")&&s.points.length>1&&<path d={s.points.map((p,i)=>`${i&&Date.parse(p.date)-Date.parse(s.points[i-1].date)<=86400000?"L":"M"}${x(p)},${y(p.cents)}`).join(" ")} fill="none" stroke={s.color} strokeWidth="2.5" strokeDasharray={s.kind==="dash"?"5 4":undefined}/>}{s.points.map((p,i)=>s.kind==="quote"?<path key={i} d={`M${x(p)},${y(p.cents)-6}l6,6 -6,6 -6,-6Z`} fill="white" stroke={s.color} strokeWidth="2.2" tabIndex={0} aria-label={`${s.label}, ${s.kind==="quote"||s.kind==="dots"?captureDay(p.date):day(p.date)}, ${amount(p.cents)}`} onMouseEnter={()=>setHover({...p,label:s.label,capture:s.kind==="quote"||s.kind==="dots"})} onFocus={()=>setHover({...p,label:s.label,capture:s.kind==="quote"||s.kind==="dots"})} onClick={()=>setHover({...p,label:s.label,capture:s.kind==="quote"||s.kind==="dots"})}><title>{s.label} · {s.kind==="quote"||s.kind==="dots"?captureDay(p.date):day(p.date)} · {amount(p.cents)}</title></path>:<circle key={i} cx={x(p)} cy={y(p.cents)} r={s.kind==="dots"?4.5:2.5} fill={s.color} stroke="white" strokeWidth="1" tabIndex={0} aria-label={`${s.label}, ${s.kind==="quote"||s.kind==="dots"?captureDay(p.date):day(p.date)}, ${amount(p.cents)}`} onMouseEnter={()=>setHover({...p,label:s.label,capture:s.kind==="quote"||s.kind==="dots"})} onFocus={()=>setHover({...p,label:s.label,capture:s.kind==="quote"||s.kind==="dots"})} onClick={()=>setHover({...p,label:s.label,capture:s.kind==="quote"||s.kind==="dots"})}><title>{s.label} · {s.kind==="quote"||s.kind==="dots"?captureDay(p.date):day(p.date)} · {amount(p.cents)}</title></circle>)}</g>)}
 </svg><div className="chart-readout" aria-live="polite">{hover?<>{hover.label} · {hover.capture?captureDay(hover.date):day(hover.date)} <strong>{amount(hover.cents)}</strong></>:"Point to a price to inspect it"}</div></>:<div className="history-empty">No visible prices in this window.<br/><span>Enable a series below or try 3M.</span></div>}
 <div className="chart-legend">{series.filter(s=>s.points.length>0).map(s=><button key={s.id} aria-pressed={enabled[s.id]} onClick={()=>{setEnabled(v=>({...v,[s.id]:!v[s.id]}));setHover(null);}}><i className={s.kind==="quote"?"quote-key":""} style={{background:s.kind==="quote"?"white":s.color,borderColor:s.color}}/>{s.label}</button>)}</div>
 <div className="history-timing"><strong>{timing.title}</strong><p>{timing.reason}</p>{timing.marketContext&&<p className="history-extra-context">{timing.marketContext}</p>}{timing.conflict&&<p className="history-conflict">{timing.conflict}</p>}{timing.datedDifference&&<p>{timing.datedDifference}</p>}</div>
 </section>;
}

export default function CardDecision({card,insight,settings,plan,note,asOf,onPlan,onNote,onArt,onClose}:{card:ReviewCard;insight:CardInsight;settings:Settings;plan:Plan;note:string;asOf:string;onPlan:(p:Plan)=>void;onNote:(s:string)=>void;onArt:()=>void;onClose:()=>void}){
 const reviewPrice=card.analystReview?.priceScenario;
 const scenarioAvailable=!!card.analystReview?.current&&reviewPrice?.grossCents!=null&&reviewPrice.grossCents!==card.medianCents;
 const [useAiScenario,setUseAiScenario]=useState(scenarioAvailable);
 const [basis,setBasis]=useState<"ask"|"median">(card.sampleCount>=5?"median":"ask");
 const [wholeLot,setWholeLot]=useState(false);
 const e=estimate(useAiScenario?{...card,medianCents:reviewPrice?.grossCents??null}:card,{...settings,basis:useAiScenario?"median":basis}),sample=estimate(card,{...settings,basis:"median"});
 const reviewNet=estimate({...card,medianCents:reviewPrice?.grossCents??null},{...settings,basis:'median'}).net;
 const factor=wholeLot?card.quantity:1;
 const {title,reason,suggested,tone,ckReady,scgHigher,dealerName,gap}=cardGuidance(card,e,sample,basis);
 const timing=timingReadout(card,asOf);
 const mixedBuylist=suggested==="buylist"&&timing.regime==="diverging";
 const leadTitle=mixedBuylist?"Buylist channel; timing is mixed":title;
 const scale=Math.max(1,card.ckCents??0,card.scgCents??0,e.net??0);
 const offers=[{name:"Card Kingdom",value:wholeLot&&!ckReady?null:card.ckCents,tone:ckReady?"ck":"ck unavailable",meta:card.ckCapacity===0?"Not buying":card.ckCapacity===null?"Quantity unconfirmed":`${card.ckCapacity} wanted · ${ckReady?"covers your lot":"partial capacity"}`,sub:ckReady?"Cash bid · before batch shipping":"Reference bid · lot not covered"},{name:"Star City Games",value:card.scgCents,tone:"scg",meta:card.scgCents===null?"No captured bid":"Confirm buying quantity",sub:wholeLot?"Quote × copies · quantity unconfirmed":"Cash quote · before batch shipping"},{name:"Sell on Mana Pool",value:e.net,tone:"retail",meta:useAiScenario?`AI price test · ${cash(e.price)} gross`:basis==="median"?`${card.sampleCount} sale${card.sampleCount===1?"":"s"} · 90d median ${cash(e.price)}`:e.price===null?"No captured price":`At the ${cash(e.price)} asking price`,sub:"Modeled net · fees & postage included"}];
 return <div className="decision-sheet">
 <header className="decision-top"><span>YOUR CARD · {card.quantity} {card.quantity===1?"COPY":"COPIES"}</span><button aria-label="Close card details" onClick={onClose}>×</button></header>
 <div className="decision-hero">{card.images.length>0&&<button className="decision-art" aria-label={`Enlarge ${card.name} card image`} onClick={onArt}><Image unoptimized src={card.images[0].normal} alt={card.name} width={110} height={154}/></button>}<div><h2>{card.name}</h2><p>{card.setCode.toUpperCase()} #{card.collectorNumber} · {card.finish==="normal"?"Nonfoil":card.finish} · {card.grade==="near_mint"?"NM":"LP"} · {card.printedLanguage.toUpperCase()}</p><div className="decision-traits">{card.semantic.traits.map(t=><span key={t}>{t}</span>)}</div><div className="decision-holding">Your direction <strong>{choices.find(c=>c.id===plan)?.label??"Undecided"}</strong></div></div></div>
 <section className="ai-analysis" aria-label="AI card analysis"><div className="decision-section-head"><span className="eyebrow">AI TAKE</span><span>{card.analystReview?.current?"Reviewed":card.analystReview?"Earlier checkpoint":"Evidence synthesis"}</span></div><h3>{card.analystReview?.headline??insight.headline}</h3><div className="ai-direction">{card.analystReview?.channel&&<div><span>Best channel</span><strong>{channelLabel(card.analystReview.channel)}</strong></div>}{card.analystReview?.timing&&<div><span>Timing</span><strong>{card.analystReview.timing}</strong></div>}</div><div className="ai-price-scenario">{reviewPrice?.grossCents!=null&&<><span>{reviewPrice.basis}</span><strong>{cash(reviewPrice.grossCents)} gross → {cash(reviewNet)} net / copy</strong></>}</div><div className="ai-next"><strong>Next move</strong><p>{card.analystReview?.nextStep??insight.nextStep}</p></div><details className="ai-deep"><summary>Why this call · evidence & countercase</summary><p className="ai-commentary">{card.analystReview?.commentary??insight.summary}</p>{card.analystReview?.counterargument&&<div className="ai-next"><strong>Strongest countercase</strong><p>{card.analystReview.counterargument}</p></div>}{card.analystReview?.reconsideration&&<div className="ai-next"><strong>What would change the call</strong><p>{card.analystReview.reconsideration}</p></div>}{card.analystReview?.buyerFit&&<div className="ai-next"><strong>Buyer fit</strong><p>{card.analystReview.buyerFit}</p></div>}<p>{insight.summary}</p><div className="ai-scenarios"><div><span>Captured sale median</span><strong>{cash(insight.median)}</strong></div><div><span>Repeated upper band · scenario</span><strong>{cash(insight.upperPrice)}</strong></div><div><span>Upper scenario extra vs CK · lot</span><strong>{insight.upperExtra!==null&&insight.upperExtra>0?"+":""}{cash(insight.upperExtra)}</strong></div><div><span>Sale price to match CK net</span><strong>{cash(insight.breakEven)}</strong></div></div><div className="ai-findings">{insight.findings.map(f=><article key={f.id} className={`finding-${f.tone}`}><strong>{f.label}</strong><p>{f.detail}</p></article>)}</div>{card.analystReview&&<p className="fine-print">Review checkpoint {captureDay(card.analystReview.asOf)} is an individual written interpretation. Proceeds and scenarios recalculate with your current settings; research signals remain separate from your plan.</p>}</details></section>
 {!card.analystReview&&<section className={`decision-lead ${tone}`}><div className="lead-symbol" aria-hidden="true">{tone==="buylist"?"↗":tone==="self"?"◇":"✦"}</div><div><span className="lead-label">CHANNEL COMPARISON</span><h3>{leadTitle}</h3><p>{reason}</p>{mixedBuylist&&<p>Dealer history weakened while the retail reference rose. Compare the timing evidence below before committing.</p>}</div>{suggested!=="undecided"&&<button onClick={()=>onPlan(suggested)}>{plan===suggested?"✓ In your plan":`Plan: ${choices.find(c=>c.id===suggested)?.label}`}</button>}</section>}
 <section className="decision-comparison"><div className="decision-section-head"><h3>What you could take home</h3>{card.quantity>1?<button className="amount-toggle" aria-pressed={wholeLot} onClick={()=>setWholeLot(!wholeLot)}>{wholeLot?`Whole lot · ${card.quantity} copies`:"Per copy"} ⇄</button>:<span>Per copy</span>}</div><div className="offer-grid">{offers.map(o=><article key={o.name} className={`offer-card ${o.tone}`}><span>{o.name}</span><strong>{cash(o.value===null?null:o.value*factor)}</strong><div className="offer-bar"><i style={{width:`${Math.max(0,(o.value??0)/scale)*100}%`}}/></div><small>{o.meta}</small><p>{o.sub}</p></article>)}</div>
 <div className="comparison-controls"><div className="segmented" aria-label="Self-sale price basis"><button aria-pressed={!useAiScenario&&basis==="median"} disabled={card.medianCents===null} onClick={()=>{setBasis("median");setUseAiScenario(false);}}>Sale samples</button><button aria-pressed={!useAiScenario&&basis==="ask"} disabled={card.askCents===null} onClick={()=>{setBasis("ask");setUseAiScenario(false);}}>Current ask</button>{scenarioAvailable&&<button aria-pressed={useAiScenario} onClick={()=>setUseAiScenario(true)}>AI price test</button>}</div>{gap!==null&&<span className="cash-difference"><strong>{gap>=0?"+":""}{cash(gap)}</strong> self-sale vs {dealerName}{scgHigher?" quote":""} · whole lot</span>}</div>
 <details className="decision-disclosure"><summary>Fees & postage breakdown</summary><dl className="receipt">{[["Sale price",e.price],["Buyer-paid shipping",e.credit],["Marketplace fee",-e.marketFee],["Processing incl. fixed charge",-e.processing],["Actual postage",-e.postage],["Materials",-e.materials],["Modeled net per order",e.net]].map(([label,n])=><div key={String(label)}><dt>{label}</dt><dd>{cash(e.price===null?null:n as number|null)}</dd></div>)}</dl><p>One copy per order. Uses your estimate settings. Labor and returns are not deducted. Dealer figures exclude the shared {cash(settings.batch)} batch-shipping allowance.</p></details></section>
 <History card={card} asOf={asOf}/>
 <SalesActivityChart card={card}/>
 <div className="decision-activity"><div><strong>{card.semantic.observedSales30}{card.semantic.saleSampleCapped&&card.semantic.observedSales30>=20?"+":""}</strong><span>sales captured · 30d</span></div><div><strong>{card.semantic.competingQuantity??"—"}</strong><span>copies listed · same grade</span></div>{card.semantic.latestObservedSaleAt&&<div><strong>{day(card.semantic.latestObservedSaleAt)}</strong><span>latest captured sale</span></div>}{card.semantic.edhrecRank!==null&&<div><strong>#{card.semantic.edhrecRank.toLocaleString()}</strong><span>EDHREC play rank</span></div>}</div>
 <section className="decision-plan"><div className="decision-section-head"><h3>Your working plan</h3><span>Saved in this browser</span></div><div className="direction-buttons">{choices.map(c=><button key={c.id} aria-pressed={plan===c.id} onClick={()=>onPlan(c.id)}><span>{c.icon}</span>{c.label}</button>)}</div>{plan!=="undecided"&&<button className="clear-direction" onClick={()=>onPlan("undecided")}>Clear direction</button>}<label htmlFor="decision-note">{plan==="hold"?"What would make you sell?":plan==="event"?"Buyer questions / target quote":"Notes / next step"}</label><textarea id="decision-note" value={note} placeholder={plan==="hold"?"A target, a reason to wait, or a date to revisit…":"What would change your decision?"} onChange={e=>onNote(e.target.value)}/></section>
 <details className="decision-disclosure sources"><summary>Sources & calculation details · {captureDay(asOf)}</summary><p>CK: {captureDay(card.ckSourceDate)} · {card.ckSource==="direct_public"?"direct product check":"TCGSentry capture"}. SCG: {captureDay(card.scgSourceDate)} · TCGSentry capture; capacity unconfirmed. Mana Pool asking price captured {captureDay(card.askCapturedAt)}.</p><p>Sales are an exact-product, same-grade sample, capped at 20 records per capture. The modeled median uses {card.sampleCount} single-copy sales within 90 days. Chart lines are retained daily MTGJSON provider prices; dots are Mana Pool single-copy sales. Diamonds are separately captured dealer quotes on their capture dates, not historical line endpoints. Additional retail series are provider retail references, not individual completed transactions. EDHREC ranks the functional card.</p><p>Next-move suggestions use a $15 whole-lot effort threshold and a five-sale sample threshold. They are comparison prompts, not completed dealer quotes or automatic inventory decisions.</p>{card.proposal&&<p><strong>Earlier reviewed proposal: {card.proposal}</strong>{card.rationale?` · ${card.rationale}`:""}</p>}{card.counterargument&&<p>{card.counterargument}</p>}{card.ckProductUrl&&<a href={card.ckProductUrl} target="_blank" rel="noreferrer">Open exact CK product ↗</a>}</details>
 </div>;
}
