"use client";
import {useState} from "react";
import Image from "next/image";
import type {ReviewCard} from "@/lib/review-data";
import {cardGuidance} from "@/lib/card-guidance";
import {estimate,type Settings} from "@/lib/selling-economics";

type Plan="undecided"|"buylist"|"self"|"event"|"hold";
const choices:{id:Plan;label:string;icon:string}[]=[{id:"buylist",label:"Buylist",icon:"↗"},{id:"self",label:"Sell myself",icon:"◇"},{id:"event",label:"MagicCon",icon:"✦"},{id:"hold",label:"Hold",icon:"◷"}];
const cash=(n:number|null)=>n===null?"—":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(n/100);
const day=(s:string|null)=>s?new Date(s).toLocaleDateString("en-US",{month:"short",day:"numeric",timeZone:"UTC"}):"—";
type Point={date:string;cents:number};

function History({card,asOf}:{card:ReviewCard;asOf:string}){
 const [days,setDays]=useState(90),[enabled,setEnabled]=useState({ck:true,tcg:true,sales:true}),[hover,setHover]=useState<Point&{label:string}|null>(null);
 const end=Date.parse(asOf),start=end-days*86400000;
 const series=[{id:"ck" as const,label:"CK buylist history",color:"#24765b",points:card.marketHistory.ck},{id:"tcg" as const,label:"TCG retail reference",color:"#7c62bb",points:card.marketHistory.tcg},{id:"sales" as const,label:"Mana Pool sales",color:"#d18c2f",points:card.recentSales}].map(s=>({...s,points:s.points.filter(p=>Date.parse(p.date)>=start&&Date.parse(p.date)<=end)}));
 const shown=series.filter(s=>enabled[s.id]),points=shown.flatMap(s=>s.points);
 const hi=Math.max(100,...points.map(p=>p.cents))*1.12,lo=0;
 const x=(p:Point)=>48+((Date.parse(p.date)-start)/(end-start))*570,y=(n:number)=>174-(n-lo)/(hi-lo)*148;
 const trend=series.find(s=>s.id==="tcg")!.points;
 const delta=trend.length>1&&trend[0].cents>0?Math.round((trend.at(-1)!.cents/trend[0].cents-1)*100):null;
 return <section className="decision-history"><div className="decision-section-head"><div><h3>Price history</h3><span>{delta!==null?`${delta>=0?"+":""}${delta}% retail reference · ${days} days`:"Exact printing · prices per copy"}</span></div><div className="segmented" aria-label="History window">{[30,90].map(n=><button key={n} aria-pressed={days===n} onClick={()=>{setDays(n);setHover(null);}}>{n===30?"1M":"3M"}</button>)}</div></div>
 {points.length?<><svg className="price-chart" viewBox="0 0 650 205" role="img" aria-label={`Price history for ${card.name}, ${days} days`}>
 {[0,.5,1].map(t=><g key={t}><line x1="48" x2="618" y1={y(hi*t)} y2={y(hi*t)} stroke="#e7ebe7" strokeDasharray="3 4"/><text x="39" y={y(hi*t)+4} textAnchor="end">${Math.round(hi*t/100)}</text></g>)}
 <text x="48" y="199">{day(new Date(start).toISOString())}</text><text x="618" y="199" textAnchor="end">{day(asOf)}</text>
 {shown.map(s=><g key={s.id}>{s.id!=="sales"&&s.points.length>1&&<path d={s.points.map((p,i)=>`${i?"L":"M"}${x(p)},${y(p.cents)}`).join(" ")} fill="none" stroke={s.color} strokeWidth="2.5" strokeDasharray={s.id==="tcg"?"5 4":undefined}/>}{s.points.map((p,i)=><circle key={i} cx={x(p)} cy={y(p.cents)} r={s.id==="sales"?4.5:3} fill={s.color} stroke="white" strokeWidth="1" tabIndex={0} aria-label={`${s.label}, ${day(p.date)}, ${cash(p.cents)}`} onMouseEnter={()=>setHover({...p,label:s.label})} onFocus={()=>setHover({...p,label:s.label})}><title>{s.label} · {day(p.date)} · {cash(p.cents)}</title></circle>)}</g>)}
 </svg><div className="chart-readout" aria-live="polite">{hover?<>{hover.label} · {day(hover.date)} <strong>{cash(hover.cents)}</strong></>:"Point to a price to inspect it"}</div></>:<div className="history-empty">No captured prices in this window.<br/><span>Try 3M or compare the current offers above.</span></div>}
 <div className="chart-legend">{series.filter(s=>s.points.length>0).map(s=><button key={s.id} aria-pressed={enabled[s.id]} onClick={()=>{setEnabled(v=>({...v,[s.id]:!v[s.id]}));setHover(null);}}><i style={{background:s.color}}/>{s.label}</button>)}</div>
 </section>;
}

export default function CardDecision({card,settings,plan,note,asOf,onPlan,onNote,onArt,onClose}:{card:ReviewCard;settings:Settings;plan:Plan;note:string;asOf:string;onPlan:(p:Plan)=>void;onNote:(s:string)=>void;onArt:()=>void;onClose:()=>void}){
 const [basis,setBasis]=useState<"ask"|"median">(card.sampleCount>=5?"median":"ask");
 const [wholeLot,setWholeLot]=useState(false);
 const e=estimate(card,{...settings,basis}),sample=estimate(card,{...settings,basis:"median"});
 const factor=wholeLot?card.quantity:1;
 const {title,reason,suggested,tone,ckReady,scgHigher,dealerName,gap}=cardGuidance(card,e,sample,basis);
 const scale=Math.max(1,card.ckCents??0,card.scgCents??0,e.net??0);
 const offers=[{name:"Card Kingdom",value:wholeLot&&!ckReady?null:card.ckCents,tone:ckReady?"ck":"ck unavailable",meta:card.ckCapacity===0?"Not buying":card.ckCapacity===null?"Quantity unconfirmed":`${card.ckCapacity} wanted · ${ckReady?"covers your lot":"partial capacity"}`,sub:ckReady?"Cash bid · before batch shipping":"Reference bid · lot not covered"},{name:"Star City Games",value:card.scgCents,tone:"scg",meta:card.scgCents===null?"No captured bid":"Confirm buying quantity",sub:wholeLot?"Quote × copies · quantity unconfirmed":"Cash quote · before batch shipping"},{name:"Sell on Mana Pool",value:e.net,tone:"retail",meta:basis==="median"?`${card.sampleCount} sale${card.sampleCount===1?"":"s"} · median ${cash(e.price)}`:e.price===null?"No captured price":`At the ${cash(e.price)} asking price`,sub:"Modeled net · fees & postage included"}];
 return <div className="decision-sheet">
 <header className="decision-top"><span>YOUR CARD · {card.quantity} {card.quantity===1?"COPY":"COPIES"}</span><button aria-label="Close card details" onClick={onClose}>×</button></header>
 <div className="decision-hero">{card.images.length>0&&<button className="decision-art" aria-label={`Enlarge ${card.name} card image`} onClick={onArt}><Image unoptimized src={card.images[0].normal} alt={card.name} width={110} height={154}/></button>}<div><h2>{card.name}</h2><p>{card.setCode.toUpperCase()} #{card.collectorNumber} · {card.finish==="normal"?"Nonfoil":card.finish} · {card.grade==="near_mint"?"NM":"LP"} · {card.printedLanguage.toUpperCase()}</p><div className="decision-traits">{card.semantic.traits.map(t=><span key={t}>{t}</span>)}</div><div className="decision-holding">Your direction <strong>{choices.find(c=>c.id===plan)?.label??"Undecided"}</strong></div></div></div>
 <section className={`decision-lead ${tone}`}><div className="lead-symbol" aria-hidden="true">{tone==="buylist"?"↗":tone==="self"?"◇":"✦"}</div><div><span className="lead-label">{card.proposal?"REVIEWED PROPOSAL":"NEXT MOVE"}</span><h3>{title}</h3><p>{reason}</p></div>{suggested!=="undecided"&&<button onClick={()=>onPlan(suggested)}>{plan===suggested?"✓ In your plan":`Plan: ${choices.find(c=>c.id===suggested)?.label}`}</button>}</section>
 <section className="decision-comparison"><div className="decision-section-head"><h3>What you could take home</h3>{card.quantity>1?<button className="amount-toggle" aria-pressed={wholeLot} onClick={()=>setWholeLot(!wholeLot)}>{wholeLot?`Whole lot · ${card.quantity} copies`:"Per copy"} ⇄</button>:<span>Per copy</span>}</div><div className="offer-grid">{offers.map(o=><article key={o.name} className={`offer-card ${o.tone}`}><span>{o.name}</span><strong>{cash(o.value===null?null:o.value*factor)}</strong><div className="offer-bar"><i style={{width:`${Math.max(0,(o.value??0)/scale)*100}%`}}/></div><small>{o.meta}</small><p>{o.sub}</p></article>)}</div>
 <div className="comparison-controls"><div className="segmented" aria-label="Self-sale price basis"><button aria-pressed={basis==="median"} disabled={card.medianCents===null} onClick={()=>setBasis("median")}>Sale samples</button><button aria-pressed={basis==="ask"} disabled={card.askCents===null} onClick={()=>setBasis("ask")}>Current ask</button></div>{gap!==null&&<span className="cash-difference"><strong>{gap>=0?"+":""}{cash(gap)}</strong> self-sale vs {dealerName}{scgHigher?" quote":""} · whole lot</span>}</div>
 <details className="decision-disclosure"><summary>Fees & postage breakdown</summary><dl className="receipt">{[["Sale price",e.price],["Shipping credit",e.credit],["Marketplace fee",-e.marketFee],["Processing incl. fixed charge",-e.processing],["Postage",-e.postage],["Materials",-e.materials],["Modeled net per order",e.net]].map(([label,n])=><div key={String(label)}><dt>{label}</dt><dd>{cash(e.price===null?null:n as number|null)}</dd></div>)}</dl><p>One copy per order. Uses your estimate settings. Labor and returns are not deducted. Dealer figures exclude the shared {cash(settings.batch)} batch-shipping allowance.</p></details></section>
 <History card={card} asOf={asOf}/>
 <div className="decision-activity"><div><strong>{card.semantic.observedSales30}{card.semantic.saleSampleCapped&&card.semantic.observedSales30>=20?"+":""}</strong><span>sales captured · 30d</span></div><div><strong>{card.semantic.competingQuantity??"—"}</strong><span>copies listed · same grade</span></div>{card.semantic.latestObservedSaleAt&&<div><strong>{day(card.semantic.latestObservedSaleAt)}</strong><span>latest captured sale</span></div>}{card.semantic.edhrecRank!==null&&<div><strong>#{card.semantic.edhrecRank.toLocaleString()}</strong><span>EDHREC play rank</span></div>}</div>
 <section className="decision-plan"><div className="decision-section-head"><h3>Your working plan</h3><span>Saved in this browser</span></div><div className="direction-buttons">{choices.map(c=><button key={c.id} aria-pressed={plan===c.id} onClick={()=>onPlan(c.id)}><span>{c.icon}</span>{c.label}</button>)}</div>{plan!=="undecided"&&<button className="clear-direction" onClick={()=>onPlan("undecided")}>Clear direction</button>}<label htmlFor="decision-note">{plan==="hold"?"What would make you sell?":plan==="event"?"Buyer questions / target quote":"Notes / next step"}</label><textarea id="decision-note" value={note} placeholder={plan==="hold"?"A target, a reason to wait, or a date to revisit…":"What would change your decision?"} onChange={e=>onNote(e.target.value)}/></section>
 <details className="decision-disclosure sources"><summary>Sources & calculation details · {day(asOf)}</summary><p>CK: {day(card.ckSourceDate)} · {card.ckSource==="direct_public"?"direct product check":"TCGSentry capture"}. SCG: {day(card.scgSourceDate)} · TCGSentry capture; capacity unconfirmed. Mana Pool asking price captured {day(card.askCapturedAt)}.</p><p>Sales are an exact-product, same-grade sample, capped at 20 records per capture. The modeled median uses {card.sampleCount} single-copy sales within 120 days. Chart lines are weekly retained MTGJSON CK indications and TCG reference prices; dots are Mana Pool single-copy sales. EDHREC ranks the functional card.</p><p>Next-move suggestions use a $15 whole-lot effort threshold and a five-sale sample threshold. They are comparison prompts, not completed dealer quotes or automatic inventory decisions.</p>{card.counterargument&&<p>{card.counterargument}</p>}{card.ckProductUrl&&<a href={card.ckProductUrl} target="_blank" rel="noreferrer">Open exact CK product ↗</a>}</details>
 </div>;
}
